// Copyright 2024 Benjamin <cyan0908@163.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Code generated by "codegen -type=int /Users/max/Documents/coding/Backend/Golang/Personal/Luna/internal/pkg/code"; DO NOT EDIT.

package code

import "github.com/lunarianss/Luna/pkg/errors" // init register error codes defines in this source code to `github.com/lunarianss/Luna/pkg/errors
func init() {
	errors.Enroll(ErrAppMapMode, 500, "Error occurred while attempt to index from appTemplate using mode")
	errors.Enroll(ErrSuccess, 200, "OK")
	errors.Enroll(ErrUnknown, 500, "Internal server error")
	errors.Enroll(ErrBind, 400, "Error occurred while binding the request body to the struct")
	errors.Enroll(ErrValidation, 400, "Validation failed")
	errors.Enroll(ErrTokenInvalid, 401, "Token invalid")
	errors.Enroll(ErrPageNotFound, 404, "Page not found")
	errors.Enroll(ErrRestfulId, 400, "Error occurred while parse restful id from url")
	errors.Enroll(ErrRunTimeCaller, 500, "Error occurred while call go inner function")
	errors.Enroll(ErrRunTimeConfig, 500, "Error occurred while runtime config is nil")
	errors.Enroll(ErrDatabase, 500, "Database error")
	errors.Enroll(ErrRecordNotFound, 500, "Database record not found")
	errors.Enroll(ErrScanToField, 400, "Database scan error to field")
	errors.Enroll(ErrEncrypt, 401, "Error occurred while encrypting the user password")
	errors.Enroll(ErrSignatureInvalid, 401, "Signature is invalid")
	errors.Enroll(ErrExpired, 401, "Token expired")
	errors.Enroll(ErrInvalidAuthHeader, 401, "Invalid authorization header")
	errors.Enroll(ErrMissingHeader, 401, "The `Authorization` header was empty")
	errors.Enroll(ErrPasswordIncorrect, 401, "Password was incorrect")
	errors.Enroll(ErrPermissionDenied, 403, "Permission denied")
	errors.Enroll(ErrEncodingFailed, 500, "Encoding failed due to an error with the data")
	errors.Enroll(ErrDecodingFailed, 500, "Decoding failed due to an error with the data")
	errors.Enroll(ErrInvalidJSON, 500, "Data is not valid JSON")
	errors.Enroll(ErrEncodingJSON, 500, "JSON data could not be encoded")
	errors.Enroll(ErrDecodingJSON, 500, "JSON data could not be decoded")
	errors.Enroll(ErrInvalidYaml, 500, "Data is not valid Yaml")
	errors.Enroll(ErrEncodingYaml, 500, "Yaml data could not be encoded")
	errors.Enroll(ErrDecodingYaml, 500, "Yaml data could not be decoded")
	errors.Enroll(ErrProviderMapModel, 500, "Error occurred while attempt to index from providerMpa using provider")
	errors.Enroll(ErrProviderNotHaveIcon, 500, "Error occurred while provider entity doesn't have icon property")
	errors.Enroll(ErrToOriginModelType, 500, "Error occurred while convert to origin model type")
	errors.Enroll(ErrDefaultModelNotFound, 500, "Error occurred while trying to convert default model to unknown")
	errors.Enroll(ErrModelSchemaNotFound, 500, "Error occurred while attempt to index from predefined models using model name")
	errors.Enroll(ErrAllModelsEmpty, 500, "Error occurred when all models are empty")
}
